// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AsideMenu: typeof import("./components/AsideMenu.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    IEpDataBoard: typeof import("~icons/ep/data-board")["default"];
    IEpFolder: typeof import("~icons/ep/folder")["default"];
    IEpSwitch: typeof import("~icons/ep/switch")["default"];
    IEpTickets: typeof import("~icons/ep/tickets")["default"];
    MainHeader: typeof import("./components/MainHeader.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
