// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AsideMenu: typeof import("./components/AsideMenu.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElRadio: typeof import("element-plus/es")["ElRadio"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    ElTree: typeof import("element-plus/es")["ElTree"];
    IEpDataBoard: typeof import("~icons/ep/data-board")["default"];
    IEpFolder: typeof import("~icons/ep/folder")["default"];
    IEpSwitch: typeof import("~icons/ep/switch")["default"];
    IEpTickets: typeof import("~icons/ep/tickets")["default"];
    IEpWarning: typeof import("~icons/ep/warning")["default"];
    MainHeader: typeof import("./components/MainHeader.vue")["default"];
    MyTable: typeof import("./components/MyTable.vue")["default"];
    RequireLabel: typeof import("./components/RequireLabel.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
